"""kartik

Revision ID: 304cd172e5ed
Revises: 872c2dbcbc74
Create Date: 2024-05-11 11:45:49.011292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '304cd172e5ed'
down_revision = '872c2dbcbc74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=4000),
               type_=sa.String(length=2000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=4000),
               existing_nullable=False)

    # ### end Alembic commands ###
